### ISSUE TITLE
Why the use of colors?

### ISSUE THREAD

**Issue by Zorgatone** [colorsafe/colorsafe#1]
Question: why the choice to use colors? Wouldn't paper colors fade with time and make the decoding harder?

I think that paperbak was safer to use with only black. It probably would store less data than the color version, but I think it would be more durable and viable for certain application where you need to store and transport some files on paper without too much risk to lose them.

What do you think?

**Comment by justinbass** [comment]
Colored ink (hue only) won't inherently fade any more than black ink, assuming saturation and value aren't used in encoding (check out Wilhelm Imaging research). The ink can smear and blend, but isn't necessarily more or less volatile. Hence I suggest using a color depth of less than 3.

However it should be mentioned that even color depth 3 will probably not work with current printer technology. My intention here was a prediction that eventually printer technology will support better color printing, and so the spec won't have to change if that happens. Also there are other use cases than archiving - someone may simply want a high-density print that will be frequently re-encoded.

Always, the default and recommended color depth for archiving and safety is 1 - black and white.

**Comment by Wikinaut** [comment]
No colours, please!

**Comment by justinbass** [comment]
Again, the default will be black and white, but colors will be supported too.

**Comment by Wikinaut** [comment]
Great!

**Comment by Zorgatone** [comment]
@justinbass ok, great to know there is a B/W fallback too! Thanks
