### ISSUE TITLE
Usage in python scripts

### ISSUE THREAD

**Issue by InnovativeInventor** [colorsafe/colorsafe#2]
How would you use this in a python script?

Edit: I'm currently doing something like this: `os.system("colorsafe encode input.txt")`

**Comment by justinbass** [comment]
I probably need to modify this file: https://github.com/colorsafe/colorsafe/blob/master/colorsafe/__init__.py to pull in cmd.py instead of colorsafe. I imagine importing the encode/decode functions is more useful than the actual implementation code.

**Comment by justinbass** [comment]
Fixed in release v0.1.0.dev5. Try:

`from colorsafe import ColorSafeDecoder, ColorSafeEncoder`

Usage examples in colorsafe/cmd.py.
