### ISSUE TITLE
Decoding exhausting memory

### ISSUE THREAD

**Issue by tuxlifan** [colorsafe/colorsafe#6]
Running `colorsafe decode images/page_c1.png` allocates all available memory (e.g. over 5.4**G**iB!) and swap until killed by OS OOM-killer.

Tested with VoidLinux on bare metal and Devuan Jessie in qemu (memory restricted to 4GiB), both with same result.
Pkgs for Devuan:
> python 2.7.9-1
> python-reportlab 3.1.8-3+deb8u1
> python-pil 2.6.1-2+deb8u3

and
> unireedsolomon 1.0 via setup.py.
> Kernel 3.16.51-3

**Comment by justinbass** [comment]
Yep. Welcome to version 0.1. I have fixed the memory issue for encoding (I think) but I'm focusing more on functionality than anything else.

**Comment by justinbass** [comment]
Basically I'm pulling in the entire file into memory with each Pixel being its own object - the current implementation is very wasteful. My plan is to decode this one pixel or row at a time and release the memory afterward.

**Comment by justinbass** [comment]
Fixed in release v0.1.0.dev5 (had done this a while ago, but never uploaded the fix for some reason). Note that encoding still exhausts memory.
