### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by justinbass** [colorsafe/colorsafe#7]
Needed since Python 2 is being EOL'd soon.

**Comment by Wikinaut** [comment]
@justinbass What are the exact steps to get github code running? It's not mentioned in the README.md.

**Comment by Wikinaut** [comment]
For your information, these are the locations of the version which I installed with ```sudo pip3 install colorsafe```:

```
sudo pip3 uninstall colorsafe
Uninstalling colorsafe-0.1.0.dev5:
  /usr/local/bin/colorsafe
  /usr/local/lib/python3.6/dist-packages/colorsafe-0.1.0.dev5.dist-info/DESCRIPTION.rst
  /usr/local/lib/python3.6/dist-packages/colorsafe-0.1.0.dev5.dist-info/INSTALLER
  /usr/local/lib/python3.6/dist-packages/colorsafe-0.1.0.dev5.dist-info/METADATA
  /usr/local/lib/python3.6/dist-packages/colorsafe-0.1.0.dev5.dist-info/RECORD
  /usr/local/lib/python3.6/dist-packages/colorsafe-0.1.0.dev5.dist-info/WHEEL
  /usr/local/lib/python3.6/dist-packages/colorsafe-0.1.0.dev5.dist-info/entry_points.txt
  /usr/local/lib/python3.6/dist-packages/colorsafe-0.1.0.dev5.dist-info/metadata.json
  /usr/local/lib/python3.6/dist-packages/colorsafe-0.1.0.dev5.dist-info/top_level.txt
  /usr/local/lib/python3.6/dist-packages/colorsafe/__init__.py
  /usr/local/lib/python3.6/dist-packages/colorsafe/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/colorsafe/__pycache__/cmd.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/colorsafe/__pycache__/colorsafe.cpython-36.pyc
  /usr/local/lib/python3.6/dist-packages/colorsafe/cmd.py
  /usr/local/lib/python3.6/dist-packages/colorsafe/colorsafe.py
  /usr/local/lib/python3.6/dist-packages/colorsafe/csdecoder.py
  /usr/local/lib/python3.6/dist-packages/colorsafe/csencoder.py
```

**Comment by justinbass** [comment]
This won't (or shouldn't) work with pip3 or Python3 yet. The exact instructions are, on a new system with pip (Tested on Ubuntu, Mac, Cygwin, Debian 9, Raspbian 7) simply:

`pip install colorsafe` or `pip install --user colorsafe`

Then:

`colorsafe encode file.txt`

**Comment by Wikinaut** [comment]
```
$ pip
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip  import main
```
(debian 10 buster)

**Comment by justinbass** [comment]
This was all mentioned in the prior thread and is out of scope for this issue, but I will elaborate again.

Generally if Colorsafe is not supported via installation with pip out of the box, I will not officially support or test on that OS. It's not my goal to handle OS level issues, as that's out of scope for this project. You can try `python setup.py install` with or without sudo depending on the OS - if that doesn't work, then I am consciously choosing not to support installation or testing on that OS. I am confident in this decision especially since I have this working on the most common 99% of OS's, and especially since Debian 10 specifically is marked as unstable. Again, I'd urge you to dual-boot Ubuntu if you want life to be easy.
